# Generated by Django 4.0.5 on 2022-06-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.CharField(max_length=9),
        ),
    ]
