# Generated by Django 4.0.3 on 2022-03-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='views_set', to='forum.views'),
            preserve_default=False,
        ),
    ]
