# Generated by Django 4.0.6 on 2022-08-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='excerpt',
        ),
    ]
