# Generated by Django 4.0.4 on 2022-04-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='url',
            new_name='slug',
        ),
    ]
