# Generated by Django 4.0.3 on 2022-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
