# Generated by Django 4.0.6 on 2022-08-08 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='topic_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
