# Generated by Django 4.0.6 on 2022-08-21 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_topic_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ManyToManyField(related_name='category_topic', to=settings.AUTH_USER_MODEL),
        ),
    ]
