# Generated by Django 4.0.6 on 2022-08-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ManyToManyField(related_name='category_topic', to='forum.topic'),
        ),
    ]
