# Generated by Django 4.0.5 on 2022-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(related_name='topic_likes', to='forum.user'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
