# Generated by Django 4.0.5 on 2022-06-09 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_feedback_usertopicrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.user', verbose_name='Поставил лайк')),
                ('topic_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.topic', verbose_name='Публикация в теме')),
            ],
            options={
                'verbose_name': 'Topic Like',
                'verbose_name_plural': 'Topic Likes',
            },
        ),
        migrations.DeleteModel(
            name='UserTopicRelation',
        ),
    ]
