# Generated by Django 4.0.3 on 2022-04-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='no-image-icon_1200.png', upload_to='media/'),
        ),
    ]
