# Generated by Django 4.0.3 on 2022-03-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_topic_views_topic_content_delete_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_views_set', to='forum.topic')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='views_set', to='forum.views'),
            preserve_default=False,
        ),
    ]
