# Generated by Django 4.0.5 on 2022-06-10 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_topiclikes_delete_usertopicrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiclikes',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
        migrations.AlterField(
            model_name='topiclikes',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Поставил лайк'),
        ),
    ]
