# Generated by Django 4.0.3 on 2022-03-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_views_topic_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
