# Generated by Django 4.0.6 on 2022-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_user_password1_user_password2_alter_ip_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/no_image.jpg', upload_to='', verbose_name='forum.User'),
        ),
    ]
