# Generated by Django 4.0.3 on 2022-04-04 15:25

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('forum', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='media/'),
        ),
    ]
