# Generated by Django 4.0.3 on 2022-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_tags_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=170),
        ),
    ]
