# Generated by Django 4.0.6 on 2022-08-09 17:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
