# Generated by Django 4.1.7 on 2023-04-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_bookmarks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.AddField(
            model_name='topic',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TopicCountViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesId', models.CharField(db_index=True, max_length=150)),
                ('postId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.topic')),
            ],
        ),
    ]
