# Generated by Django 4.0.6 on 2022-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_category_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='role',
            field=models.CharField(choices=[('A', 'Author')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
