# Generated by Django 4.0.6 on 2022-08-11 17:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_topic_managers_topic_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
