# Generated by Django 4.1.7 on 2023-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_viewer_remove_topic_count_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
