# Generated by Django 4.0.3 on 2022-04-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_category_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated',
        ),
    ]
