# Generated by Django 4.1.7 on 2023-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_category_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='viewers',
            field=models.ManyToManyField(blank=True, to='forum.viewer'),
        ),
    ]
