# Generated by Django 4.0.6 on 2022-08-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_reply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
