# Generated by Django 4.0.6 on 2022-08-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_topic_date_end_topic_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='date_start',
        ),
    ]
