# Generated by Django 4.0.4 on 2022-04-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.SlugField(default=1, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
