# Generated by Django 4.0.6 on 2022-08-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_topic_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
            ],
        ),
    ]
