# Generated by Django 4.0.6 on 2022-08-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_topic_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='role',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
    ]
