# Generated by Django 4.0.6 on 2022-08-13 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_topic_managers_remove_topic_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replies',
            options={'ordering': ('-id',), 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.RemoveField(
            model_name='replies',
            name='author_name',
        ),
        migrations.AddField(
            model_name='replies',
            name='author',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replies',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='replies',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_set', to='forum.topic'),
        ),
    ]
