# Generated by Django 4.1.7 on 2023-05-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='countuser',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='countuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='count_user',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='CountUser',
        ),
    ]
