# Generated by Django 4.1 on 2022-09-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_topic_reply_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_views_set', to='forum.topic')),
                ('views', models.ManyToManyField(blank=True, related_name='post_views', to='forum.ip')),
            ],
        ),
    ]
