# Generated by Django 4.0.6 on 2022-08-13 17:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_replies_options_remove_replies_author_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
