# Generated by Django 4.0.6 on 2022-08-14 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_topic_managers_topic_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='topic',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
