# Generated by Django 4.1 on 2022-09-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_ip_updated_remove_ip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='forum.ip'),
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
