# Generated by Django 4.0.6 on 2022-08-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_topic_options_topic_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='draft', max_length=10),
        ),
    ]
