# Generated by Django 4.1 on 2022-09-10 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_remove_topic_count_views_delete_topiccountviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
