# Generated by Django 4.0.6 on 2022-08-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('url', 'user')},
        ),
    ]
