# Generated by Django 4.1 on 2022-09-10 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_countuser_topic_count_user_alter_topic_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countuser',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_topic_user', to='forum.topic'),
        ),
        migrations.AlterField(
            model_name='countuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_user_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
