# Generated by Django 4.0.6 on 2022-08-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_alter_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
