# Generated by Django 4.1 on 2022-09-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_alter_countuser_topic_alter_countuser_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countuser',
            unique_together={('user', 'topic')},
        ),
    ]
