# Generated by Django 4.0.6 on 2022-08-15 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_bookmark_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.CreateModel(
            name='Dopmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ManyToManyField(blank=True, default=None, related_name='topic_bookmark', to='forum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_topic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
