# Generated by Django 4.0.6 on 2022-08-15 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_alter_topic_managers_remove_topic_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dopmarks',
            field=models.ManyToManyField(blank=True, default=None, related_name='topic_dopmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
