# Generated by Django 4.0.6 on 2022-08-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_topic_dopmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='topic',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark_topic_bookmark', to='forum.topic'),
        ),
    ]
