# Generated by Django 4.1 on 2022-09-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_topicstatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicStatistic',
        ),
    ]
