# Generated by Django 4.0.6 on 2022-08-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_bookmark_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='dopmarks',
        ),
    ]
