# Generated by Django 4.1 on 2022-09-11 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_delete_topicstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='reply_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
