# Generated by Django 4.1 on 2022-09-14 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_alter_topic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=130, unique=True),
        ),
    ]
