# Generated by Django 4.1 on 2022-09-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_remove_topic_read_users_delete_userreadtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddres', models.GenericIPAddressField(default='45.243.82.169')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topic')),
            ],
            options={
                'verbose_name_plural': 'Просмотры Топика',
            },
        ),
    ]
