# Generated by Django 4.1 on 2022-09-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_topicviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicViews',
        ),
    ]
