# Generated by Django 4.1 on 2022-10-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0034_delete_topicviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='file',
        ),
    ]
