# Generated by Django 4.0.6 on 2022-08-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/no_image.jpg', null=True, upload_to='', verbose_name='forum.User'),
        ),
    ]
