# Generated by Django 4.0.6 on 2022-07-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='no_image.jpg', upload_to='media'),
        ),
    ]
