# Generated by Django 4.0.6 on 2022-07-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
    ]
