# Generated by Django 4.0.6 on 2022-08-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
