# Generated by Django 4.0.6 on 2022-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
    ]
