# Generated by Django 4.0.6 on 2022-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='no_image.jpg', upload_to='media'),
        ),
    ]
