# Generated by Django 4.0.6 on 2022-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0009_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/no_image.jpg', upload_to='', verbose_name='forum.User'),
        ),
    ]
