# Generated by Django 4.0.6 on 2022-08-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0015_alter_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
